import type { Metadata } from "next";
import "./globals.css";

// 导入全局初始化（自动启动Worker）
import "@/lib/init";

// 移除自定义字体配置,使用系统默认字体以兼容 Turbopack
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
